name: terraform-fmt
on:
  pull_request:
  push:

jobs:
  build:
    name: Terraform Format Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: false
      working-directory: ./terraform
